### PR TITLE
add resources section to homepage

### PR DESCRIPTION
**Pull request by lhmzhou**
Hi @almnt! 👋
This PR adds a section on the main site that lists out anti-racism resources ranging from videos, podcasts, and books. Please check it out, and lend me your thoughts.

### CODE REVIEW

**Comment by lhmzhou** [comment]
> Hiya! Thanks for this. The guide is meant to be open, not specifically just focused on race (for example, Black people also experience racism, while Black women experience that and gender discrimination (even within the current swell of support for Black lives), and queer GNC Black people who appear as "women" experience the previous two axes of discrimination along with queer discrimination.
> 
> I'm realizing that this guide needs to be bigger than I intended, so I'm going to hold off on these changes and start working on some new changes that can incorporate these.

**Comment by lhmzhou** [comment]
Sounds reasonable. Can you provide more specific guidelines on the "new changes" you are aiming for?

**Comment by almnt** [comment]
> Sounds absolutely reasonable. Can you provide more specific guidelines on the "new changes" you are aiming for?

@lhmzhou Yeah, I don't think the site can function as a one-pager, anymore. There needs to be categories for various identities and a clear way to show how those identities intersect in a larger conversation, but also allowing the reader to read about specific identities in more detail.

I started working on designs for this about a year ago and put them on hold because the one-pager seemed sufficient. But I think people need/want resources. Curious to hear your thoughts, too.

**Comment by lhmzhou** [comment]
100% agreed, there is waaay too much ground to cover on a single page. To avoid overwhelming users, a scalable, multi-page is the direction we may want to posture towards. Let me know how we can help bring your on-hold designs to life 🤓

**Comment by almnt** [comment]
I wanted to follow up on this @lhmzhou! Thanks so much for sharing your thoughts. It was helpful to get another perspective.

I've been doing some thinking. When I created this guide, I meant for it to be a general guide. The more I thought about it this week, I think the guide can be a starting place for those interested in learning to be allies, but I don't think it can be everything to everyone. I worry the site is moving into a territory of trying to educate on all aspects of allyship when moving away from a one-pager.

So the compromise I think that might be good would be a resources section (just as you had initially shared in this PR), but linking to a variety of resources beyond just race that can help further someone's education.

It also directs the burden of education to the experts who have spent their life's work doing this and don't have as much visibility.

If that sounds good, I can add a starter resource section this week. 😄

**Comment by lhmzhou** [comment]
Bombs away! Let's go for it 😍 
I know you have complete command of your mad dev skills, but please let me know if you may need a hand in carving out the new resource portion of the guide. In the meantime, I'll re-evauluate and tune up my current list. I'll drop the working list in this newly created issue [here](https://github.com/almnt/guide-to-allyship/issues/26).

**Comment by almnt** [comment]
Yesss, thanks @lhmzhou! 💖 I added a card for this in the roadmap linking to your issue. I'll start working on a list, as well. 😃

**Pull request closed without merging**
